version: "3"
services:
  project-match:
    image: sfbrigade/project-match:app
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - .:/app
      # We exclude all the node_modules directories in our .dockerignore file, so that we don't
      # clobber local node_modules for developers who have been running this locally.
      # And, volumes are mounted at runtime, not build time.
      # So building the image runs "npm install" and creates these node_modules directories
      # *inside the image*, but then when the container is run, it mounts .:/app in the line
      # above and overlays the host's root project directory, without the host's node_modules
      # directories (which were built OUTSIDE the container and are probably not compatible).
      # Thus, we have to mount the node_modules that were built inside the image.
      - /app/node_modules
      - /app/components/api/node_modules
      - /app/components/main_website/node_modules
      - /app/components/messaging/node_modules
      - /app/components/project-list/node_modules
      - /app/components/admin/node_modules
      - /app/components/common/node_modules
      - /app/components/minmaximizer/node_modules
      - /app/components/mongodb/node_modules
      - /app/components/notifications/node_modules
      - /app/components/system-proxy/node_modules
    networks:
      - app-network
    environment:
      - BRIGADE=codeforexample
      - MONGODB=mongodb://mongo:27017/brigade-matchmaker
      - MONGOLAB_URI=mongodb://mongo:27017/brigade-matchmaker
  mongo:
    image: mongo:3.2.20-jessie
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - project-match
    ports:
      - "80:80"
      - "443:443"
      - "5455:5455" # api
      - "5475:5475" # messaging
      - "5495:5495" # selector UI prototype
    volumes:
      # Nginx config file lives here.
      - ./nginx-conf:/etc/nginx/conf.d
      # Locally-generated and stored SSL keys used by nginx.
      - ./localhost_keys/localhost.key:/etc/letsencrypt/live/localhost/privkey.pem
      - ./localhost_keys/localhost.crt:/etc/letsencrypt/live/localhost/fullchain.pem
      - ./dhparam/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodb-data:
