version: "3"
services:
  brigade-matchmaker:
    depends_on:
      - mongo
    image: sfbrigade/brigade-matchmaker:app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080" # main_website
      - "5455:5455" # api
      - "5475:5475" # messaging
      - "5495:5495" # selector UI prototype
    volumes:
      - .:/app
      # Volumes are mounted at runtime, not build time.
      # So building the image runs "npm install" and creates
      # these node_modules directories *inside the image*, but then
      # when the container is run, it mounts .:/app
      # above and overlays the host's root source directory.
      # The host doesn't have the node_module directories.
      - /app/node_modules
      - /app/components/api/node_modules
      - /app/components/main_website/node_modules
      - /app/components/messaging/node_modules
      - /app/components/project-list/node_modules
      - /app/components/admin/node_modules
      - /app/components/common/node_modules
      - /app/components/minmaximizer/node_modules
      - /app/components/mongodb/node_modules
      - /app/components/notifications/node_modules
      - /app/components/system-proxy/node_modules
    networks:
      - webnet
    environment:
      - BRIGADE=codeforexample
      - MONGODB=mongodb://mongo:27017/brigade-matchmaker
      - MONGOLAB_URI=mongodb://mongo:27017/brigade-matchmaker
  mongo:
    image: mongo:3.2.20-jessie
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
volumes:
  mongodb-data:
