#!/bin/bash
echo 'Setting up for deployment to heroku'
echo 'Run from components/web/scripts dir'
mPath='../../messaging/config'
wPath='../'
echo 'swap envs for messaging'
cp $mPath/heroku.development.js $mPath/development.js
cp $mPath/heroku.env.js.default $mPath/env.js.default
echo 'swap env for web'
cp $wPath/heroku.env.example $wPath/.env
echo 'swap api local for api heroku (for pyDir)'
cp $wPath/controllers/apiH.js $wPath/controllers/api.js 
