# Generated by Django 2.0.6 on 2018-06-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsNeeded', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsNeeded', models.ManyToManyField(max_length=2000, to='data.GoalsNeeded')),
                ('interests', models.ManyToManyField(max_length=2000, to='data.Interests')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingDescr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
                ('repository', models.CharField(max_length=2000)),
                ('contactThumbNailUrl', models.CharField(max_length=2000)),
                ('contactRole', models.CharField(max_length=2000)),
                ('contactSlack', models.CharField(max_length=2000)),
                ('contactEmail', models.CharField(max_length=2000)),
                ('contactName', models.CharField(max_length=2000)),
                ('summary', models.CharField(max_length=2000)),
                ('thumbnailUrl', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('repository', models.CharField(max_length=2000)),
                ('homepage', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=2000)),
                ('matchingConfig', models.ForeignKey(max_length=2000, on_delete=django.db.models.deletion.CASCADE, to='data.MatchingConfig')),
                ('matchingDescr', models.ForeignKey(max_length=2000, on_delete=django.db.models.deletion.CASCADE, to='data.MatchingDescr')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsNeeded', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillsOffered', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbNailUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbNailUrl', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.ForeignKey(max_length=2000, on_delete=django.db.models.deletion.CASCADE, to='data.Team'),
        ),
        migrations.AddField(
            model_name='matchingdescr',
            name='progress',
            field=models.ManyToManyField(max_length=2000, to='data.Progress'),
        ),
        migrations.AddField(
            model_name='matchingdescr',
            name='tasks',
            field=models.ManyToManyField(max_length=2000, to='data.Tasks'),
        ),
        migrations.AddField(
            model_name='matchingconfig',
            name='needs',
            field=models.ManyToManyField(max_length=2000, to='data.Needs'),
        ),
        migrations.AddField(
            model_name='matchingconfig',
            name='skillsNeeded',
            field=models.ManyToManyField(max_length=2000, to='data.SkillsNeeded'),
        ),
        migrations.AddField(
            model_name='matchingconfig',
            name='skillsOffered',
            field=models.ManyToManyField(max_length=2000, to='data.SkillsOffered'),
        ),
        migrations.AddField(
            model_name='matchingconfig',
            name='thumbNailUrl',
            field=models.ForeignKey(max_length=2000, on_delete=django.db.models.deletion.CASCADE, to='data.ThumbNailUrl'),
        ),
    ]
