# Generated by Django 2.0.6 on 2018-06-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180612_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=2000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('summary', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('project_status', models.CharField(max_length=50)),
                ('repository', models.CharField(max_length=2000)),
                ('website', models.CharField(max_length=2000)),
                ('slack_channel', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='goalsNeeded',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='needs',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='skillsNeeded',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='skillsOffered',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='thumbNailUrl',
        ),
        migrations.RemoveField(
            model_name='matchingdescr',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='matchingdescr',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='matchingConfig',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='matchingDescr',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='GoalsNeeded',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='MatchingConfig',
        ),
        migrations.DeleteModel(
            name='MatchingDescr',
        ),
        migrations.DeleteModel(
            name='Needs',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='SkillsNeeded',
        ),
        migrations.DeleteModel(
            name='SkillsOffered',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='ThumbNailUrl',
        ),
    ]
