# Generated by Django 2.1 on 2018-08-06 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('parent', models.CharField(max_length=254)),
                ('class_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InterestsTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('parent', models.CharField(max_length=254)),
                ('class_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=454, null=True)),
                ('summary', models.CharField(max_length=254)),
                ('image_url', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('project_status', models.CharField(max_length=50)),
                ('repository', models.CharField(max_length=2000)),
                ('website', models.CharField(max_length=2000)),
                ('slack_channel', models.CharField(max_length=200)),
                ('created', models.DateTimeField(null=True)),
                ('civic_interests', models.ManyToManyField(to='api.InterestsTaxonomy')),
                ('learning_opportunities', models.ManyToManyField(to='api.GoalsTaxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('github_user_name', models.CharField(max_length=254)),
                ('email_address', models.EmailField(max_length=254)),
                ('slack_name', models.CharField(max_length=254)),
                ('slack_id', models.CharField(max_length=20)),
                ('created', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectLeads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('parent', models.CharField(max_length=254)),
                ('class_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProjectLead'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_needed',
            field=models.ManyToManyField(to='api.SkillsTaxonomy'),
        ),
    ]
