# Generated by Django 2.1 on 2018-08-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstaxonomy',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='intereststaxonomy',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='skillstaxonomy',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='goalstaxonomy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intereststaxonomy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectlead',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillstaxonomy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
