# Generated by Django 2.1 on 2018-09-11 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180807_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_name', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('email_address', models.EmailField(max_length=254)),
                ('slack_name', models.CharField(max_length=254)),
                ('slack_id', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectlead',
            name='owner',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile'),
        ),
        migrations.DeleteModel(
            name='ProjectLead',
        ),
    ]
