# Generated by Django 2.1.2 on 2018-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180919_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoalsTaxonomy',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='InterestsTaxonomy',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='SkillsTaxonomy',
            new_name='Skill',
        ),
        migrations.AddField(
            model_name='project',
            name='github_repository',
            field=models.CharField(max_length=454, null=True),
        ),
    ]
