# Generated by Django 2.1.2 on 2018-10-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181014_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.CharField(max_length=454, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(max_length=454, null=True),
        ),
    ]
